;;; riscv-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from riscv-mode.el

(autoload 'riscv-mode "riscv-mode" "\
Major mode for editing RISC V assembly.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.riscv\\'" . riscv-mode))
(register-definition-prefixes "riscv-mode" '("riscv-"))

;;; End of scraped data

(provide 'riscv-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; riscv-mode-autoloads.el ends here
